In [20]:
import pandas as pd

In [21]:
# Load the dataset
population_file_path = "population_USA.csv"  # Update this with your actual file path
population_df = pd.read_csv(population_file_path)

In [22]:
population_df.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,...,RNATURALCHG2023,RINTERNATIONALMIG2021,RINTERNATIONALMIG2022,RINTERNATIONALMIG2023,RDOMESTICMIG2021,RDOMESTICMIG2022,RDOMESTICMIG2023,RNETMIG2021,RNETMIG2022,RNETMIG2023
0,10,0,0,0,United States,331464948,331526933,332048977,333271411,334914895,...,1.510043,1.133278,3.003867,3.409196,0.000000,0.000000,0.000000,1.133278,3.003867,3.409196
1,20,1,0,0,Northeast Region,57614141,57430477,57243423,57026847,56983517,...,0.976280,1.403074,3.678035,3.947167,-4.823207,-7.881683,-5.671414,-3.420133,-4.203648,-1.724247
2,30,1,1,0,New England,15119994,15057898,15106108,15120739,15159777,...,-0.019551,1.772643,4.532659,5.024221,1.615767,-3.086263,-2.445863,3.388409,1.446396,2.578358
3,30,1,2,0,Middle Atlantic,42494147,42372579,42137315,41906108,41823740,...,1.336417,1.271165,3.370662,3.557656,-7.121462,-9.606391,-6.837920,-5.850297,-6.235729,-3.280264
4,20,2,0,0,Midwest Region,68987296,68969794,68850246,68783028,68909283,...,0.665803,0.802684,2.098649,2.409866,-2.577042,-2.636615,-1.245226,-1.774357,-0.537966,1.164640

In [23]:
# Keep only the row where NAME is "United States"
population_usa_df = population_df[population_df["NAME"] == "United States"]

In [24]:
# Pivot the data to get 'Year' and 'Population' as columns
population_long_df = pd.melt(
    population_usa_df,
    id_vars=["NAME"],  # Keep only NAME column
    value_vars=["POPESTIMATE2020", "POPESTIMATE2021", "POPESTIMATE2022", "POPESTIMATE2023"],
    var_name="Year",
    value_name="Population"
)

In [25]:
population_long_df.head()

            NAME             Year  Population
0  United States  POPESTIMATE2020   331526933
1  United States  POPESTIMATE2021   332048977
2  United States  POPESTIMATE2022   333271411
3  United States  POPESTIMATE2023   334914895

In [26]:
# Extract the numeric year from column names
population_long_df["Year"] = population_long_df["Year"].str.extract("(\d{4})").astype(int)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/var/folders/bh/47f15t0x7r73gljdmx_h6tx00000gn/T/ipykernel_60468/2727539048.py:2: SyntaxWarning: invalid escape sequence '\d'
  population_long_df["Year"] = population_long_df["Year"].str.extract("(\d{4})").astype(int)

In [27]:
population_cleaned_df = population_long_df[["Year", "Population"]]

In [28]:
population_cleaned_df.head()

   Year  Population
0  2020   331526933
1  2021   332048977
2  2022   333271411
3  2023   334914895

In [19]:
# Save the cleaned data to an Excel file
cleaned_population_file_path = "Cleaned_Population_USA.xlsx"
population_cleaned_df.to_excel(cleaned_population_file_path, index=False)